export const SNAP_QUESTIONS = [
  "1. Não consegue prestar muita atenção a detalhes ou comete erros por descuido nos trabalhos da escola ou tarefas.",
  "2. Tem dificuldade de manter a atenção em tarefas ou atividades de lazer.",
  "3. Parece não estar ouvindo quando se fala diretamente com ele.",
  "4. Não segue instruções até o fim e não termina deveres de escola, tarefas ou obrigações.",
  "5. Tem dificuldade para organizar tarefas e atividades.",
  "6. Evita, não gosta ou se envolve contra a vontade em tarefas que exigem esforço mental prolongado.",
  "7. Perde coisas necessárias para atividades (brinquedos, deveres da escola, lápis ou livros).",
  "8. Distrai-se com estímulos externos.",
  "9. É esquecido em atividades do dia a dia.",
  "10. Mexe com as mãos ou os pés ou se remexe na cadeira.",
  "11. Sai do lugar na sala de aula ou em outras situações em que se espera que fique sentado.",
  "12. Corre de um lado para o outro ou sobe demais nas coisas em situações em que isto é inapropriado.",
  "13. Tem dificuldade em brincar ou envolver-se em atividades de lazer de forma calma.",
  "14. Não para ou frequentemente está a \"mil por hora\".",
  "15. Fala em excesso.",
  "16. Responde perguntas de forma precipitada antes que elas tenham sido terminadas.",
  "17. Tem dificuldade em esperar sua vez.",
  "18. Interrompe os outros ou se intromete (nas conversas, jogos, etc.).",
  "19. Descontrola-se.",
  "20. Discute com adultos.",
  "21. Desafia ativamente ou se recusa a atender pedidos ou regras de adultos.",
  "22. Faz de propósito coisas que incomodam as outras pessoas.",
  "23. Responsabiliza outras pessoas por seus erros ou mau comportamento.",
  "24. É melindroso ou facilmente incomodado pelos outros.",
  "25. É raivoso ou ressentido.",
  "26. É maldoso ou vingativo."
];
